Add debug statements + pure soot repro
Generate some class files, which contain a invokedynamic instruction, via
the following script

$> cat script.sh
#!/bin/bash
for i in $(seq 30); do
	cat > "Test$i.java" <<EOF
public class Test$i {
	public String run$i() {
		String x = "foo";
		String y = x + "Test$i";
		System.out.println(y);
		return y;
	}

	public static void main(String[] args) {
		new Test$i().run$i();
	}
}
EOF
	javac11 -d out "Test$i.java"
done
$> bash script.sh
$>

Next, execute soot (the --validate option (+ a bit luck;) ) is crucial to
trigger this behavior (it triggers the method resolution)).

Note that the stacktrace contains two races.
Thread-1 races with Thread-7 (note that this does not result in a
"duplicate class" RuntimeException because the RefType's sootClass is
updated/replaced when creating a new SootClass instance (Thread-7)).

Thread-4 races with Thread-1 + Thread-7 and causes this particular exception.

$> soot11 --validate -f J --process-dir out
Soot started on Tue Jun 16 13:18:17 CEST 2020
RETRIEVE all bodies [1, main, 1795816257]
RefType before getOrAddRefType: soot.dummy.InvokeDynamic [14, Thread-1, 1854504039]
RefType before getOrAddRefType: soot.dummy.InvokeDynamic [20, Thread-7, 576709868]
RefType: soot.dummy.InvokeDynamic, 1561376148 [14, Thread-1, 1854504039]
RefType: soot.dummy.InvokeDynamic, 1561376148 [20, Thread-7, 576709868]
CREATED soot.dummy.InvokeDynamic... 1387649290 [17, Thread-4, 1082626496]
CREATED soot.dummy.InvokeDynamic... 1095463937 [14, Thread-1, 1854504039]
SETRESOLVINGLEVEL: soot.dummy.InvokeDynamic: 3 [17, Thread-4, 1082626496]
SETRESOLVINGLEVEL: soot.dummy.InvokeDynamic: 0 [17, Thread-4, 1082626496]
SETRESOLVINGLEVEL: soot.dummy.InvokeDynamic: 3 [14, Thread-1, 1854504039]
DRIN: convertInvokeDynamicInsn: 1981747394 [17, Thread-4, 1082626496]
DRIN: convertInvokeDynamicInsn: 438751725 [14, Thread-1, 1854504039]
CREATED soot.dummy.InvokeDynamic... 151954390 [20, Thread-7, 576709868]
SETRESOLVINGLEVEL: soot.dummy.InvokeDynamic: 3 [20, Thread-7, 576709868]
DRIN: convertInvokeDynamicInsn: 1159810427 [20, Thread-7, 576709868]
RETRIEVE active body (ms done): Test2.run2 [17, Thread-4, 1082626496]
DRIN: convertInvokeDynamicInsn: 1584287134 [15, Thread-2, 2058010926]
RETRIEVE active body (ms done): Test4.run4 [20, Thread-7, 576709868]
DRIN: convertInvokeDynamicInsn: 2097243009 [20, Thread-7, 576709868]
RETRIEVE active body (ms done): Test19.run19 [14, Thread-1, 1854504039]
DRIN: convertInvokeDynamicInsn: 322885692 [17, Thread-4, 1082626496]
RETRIEVE active body (ms done): Test20.run20 [20, Thread-7, 576709868]
RETRIEVE active body (ms done): Test25.run25 [17, Thread-4, 1082626496]
RETRIEVE active body (ms done): Test3.run3 [15, Thread-2, 2058010926]
DRIN: convertInvokeDynamicInsn: 1955839877 [17, Thread-4, 1082626496]
DRIN: convertInvokeDynamicInsn: 1398581728 [20, Thread-7, 576709868]
RETRIEVE active body (ms done): Test8.run8 [17, Thread-4, 1082626496]
DRIN: convertInvokeDynamicInsn: 1296558640 [17, Thread-4, 1082626496]
RETRIEVE active body (ms done): Test7.run7 [20, Thread-7, 576709868]
DRIN: convertInvokeDynamicInsn: 523453070 [20, Thread-7, 576709868]
RETRIEVE active body (ms done): Test17.run17 [17, Thread-4, 1082626496]
DRIN: convertInvokeDynamicInsn: 651861031 [17, Thread-4, 1082626496]
RETRIEVE active body (ms done): Test22.run22 [20, Thread-7, 576709868]
DRIN: convertInvokeDynamicInsn: 2101881434 [20, Thread-7, 576709868]
RETRIEVE active body (ms done): Test12.run12 [17, Thread-4, 1082626496]
DRIN: convertInvokeDynamicInsn: 1446018802 [14, Thread-1, 1854504039]
RETRIEVE active body (ms done): Test9.run9 [20, Thread-7, 576709868]
RETRIEVE active body (ms done): Test26.run26 [14, Thread-1, 1854504039]
DRIN: convertInvokeDynamicInsn: 1821695966 [20, Thread-7, 576709868]
DRIN: convertInvokeDynamicInsn: 273703341 [19, Thread-6, 991963169]
DRIN: convertInvokeDynamicInsn: 1033662690 [13, Thread-0, 739096823]
DRIN: convertInvokeDynamicInsn: 16172355 [16, Thread-3, 765081093]
DRIN: convertInvokeDynamicInsn: 2016079584 [14, Thread-1, 1854504039]
RETRIEVE active body (ms done): Test6.run6 [19, Thread-6, 991963169]
RETRIEVE active body (ms done): Test27.run27 [13, Thread-0, 739096823]
RETRIEVE active body (ms done): Test1.run1 [14, Thread-1, 1854504039]
DRIN: convertInvokeDynamicInsn: 551955557 [15, Thread-2, 2058010926]
DRIN: convertInvokeDynamicInsn: 1549164757 [14, Thread-1, 1854504039]
RETRIEVE active body (ms done): Test16.run16 [15, Thread-2, 2058010926]
DRIN: convertInvokeDynamicInsn: 1540609524 [15, Thread-2, 2058010926]
RETRIEVE active body (ms done): Test14.run14 [14, Thread-1, 1854504039]
DRIN: convertInvokeDynamicInsn: 1542210081 [14, Thread-1, 1854504039]
RETRIEVE active body (ms done): Test28.run28 [15, Thread-2, 2058010926]
DRIN: convertInvokeDynamicInsn: 2113859570 [15, Thread-2, 2058010926]
RETRIEVE active body (ms done): Test11.run11 [14, Thread-1, 1854504039]
DRIN: convertInvokeDynamicInsn: 1000518446 [14, Thread-1, 1854504039]
RETRIEVE active body (ms done): Test18.run18 [15, Thread-2, 2058010926]
DRIN: convertInvokeDynamicInsn: 1110718975 [17, Thread-4, 1082626496]
RETRIEVE active body (ms done): Test15.run15 [14, Thread-1, 1854504039]
DRIN: convertInvokeDynamicInsn: 1936874241 [14, Thread-1, 1854504039]
RETRIEVE active body (ms done): Test24.run24 [17, Thread-4, 1082626496]
RETRIEVE active body (ms done): Test21.run21 [20, Thread-7, 576709868]
DRIN: convertInvokeDynamicInsn: 360909266 [18, Thread-5, 1932677070]
DRIN: convertInvokeDynamicInsn: 1146319735 [19, Thread-6, 991963169]
RETRIEVE active body (ms done): Test29.run29 [14, Thread-1, 1854504039]
RETRIEVE active body (ms done): Test13.run13 [18, Thread-5, 1932677070]
DRIN: convertInvokeDynamicInsn: 886388956 [18, Thread-5, 1932677070]
RETRIEVE active body (ms done): Test5.run5 [16, Thread-3, 765081093]
RETRIEVE active body (ms done): Test23.run23 [19, Thread-6, 991963169]
DRIN: convertInvokeDynamicInsn: 517950842 [20, Thread-7, 576709868]
RETRIEVE active body (ms done): Test10.run10 [18, Thread-5, 1932677070]
RETRIEVE active body (ms done): Test30.run30 [20, Thread-7, 576709868]
RUNBODY packs:  [1, main, 1795816257]
RESOLVE SootMethod: makeConcatWithConstants [24, Thread-11, 1526460177]
RESOLVE SootMethod: makeConcatWithConstants [22, Thread-9, 605241803]
LEVEL ERROR: soot.dummy.InvokeDynamic, 1387649290 [22, Thread-9, 605241803]
RESOLVE SootMethod: makeConcatWithConstants [25, Thread-12, 1770603249]
RESOLVE SootMethod: makeConcatWithConstants [21, Thread-8, 742168263]
RESOLVE SootMethod: makeConcatWithConstants [23, Thread-10, 1471281128]
[Thread-9] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: This operation requires resolving level SIGNATURES but soot.dummy.InvokeDynamic is at resolving level DANGLING
If you are extending Soot, try to add the following call before calling soot.Main.main(..):
Scene.v().addBasicClass(soot.dummy.InvokeDynamic,SIGNATURES);
Otherwise, try whole-program mode (-w).
RESOLVE SootMethod: makeConcatWithConstants [28, Thread-15, 679833660]
RESOLVE SootMethod: makeConcatWithConstants [26, Thread-13, 1497478396]
java.lang.RuntimeException: This operation requires resolving level SIGNATURES but soot.dummy.InvokeDynamic is at resolving level DANGLING
If you are extending Soot, try to add the following call before calling soot.Main.main(..):
Scene.v().addBasicClass(soot.dummy.InvokeDynamic,SIGNATURES);
Otherwise, try whole-program mode (-w).
	at soot.SootClass.checkLevelIgnoreResolving(SootClass.java:212)
	at soot.SootClass.checkLevel(SootClass.java:191)
	at soot.SootClass.getMethodUnsafe(SootClass.java:580)
	at soot.SootMethodRefImpl.tryResolve(SootMethodRefImpl.java:210)
	at soot.SootMethodRefImpl.resolve(SootMethodRefImpl.java:268)
	at soot.SootMethodRefImpl.resolve(SootMethodRefImpl.java:183)
	at soot.jimple.internal.AbstractInvokeExpr.getMethod(AbstractInvokeExpr.java:56)
	at soot.jimple.validation.InvokeArgumentValidator.validate(InvokeArgumentValidator.java:54)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:118)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:98)
	at soot.PackManager.runBodyPacks(PackManager.java:1011)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:663)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
RESOLVE SootMethod: makeConcatWithConstants [27, Thread-14, 854144180]
Exception in thread "Thread-9" java.lang.RuntimeException: This operation requires resolving level SIGNATURES but soot.dummy.InvokeDynamic is at resolving level DANGLING
If you are extending Soot, try to add the following call before calling soot.Main.main(..):
Scene.v().addBasicClass(soot.dummy.InvokeDynamic,SIGNATURES);
Otherwise, try whole-program mode (-w).
	at soot.SootClass.checkLevelIgnoreResolving(SootClass.java:212)
	at soot.SootClass.checkLevel(SootClass.java:191)
	at soot.SootClass.getMethodUnsafe(SootClass.java:580)
	at soot.SootMethodRefImpl.tryResolve(SootMethodRefImpl.java:210)
	at soot.SootMethodRefImpl.resolve(SootMethodRefImpl.java:268)
	at soot.SootMethodRefImpl.resolve(SootMethodRefImpl.java:183)
	at soot.jimple.internal.AbstractInvokeExpr.getMethod(AbstractInvokeExpr.java:56)
	at soot.jimple.validation.InvokeArgumentValidator.validate(InvokeArgumentValidator.java:54)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:118)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:98)
	at soot.PackManager.runBodyPacks(PackManager.java:1011)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:663)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.RuntimeException: This operation requires resolving level SIGNATURES but soot.dummy.InvokeDynamic is at resolving level DANGLING
If you are extending Soot, try to add the following call before calling soot.Main.main(..):
Scene.v().addBasicClass(soot.dummy.InvokeDynamic,SIGNATURES);
Otherwise, try whole-program mode (-w).
	at soot.SootClass.checkLevelIgnoreResolving(SootClass.java:212)
	at soot.SootClass.checkLevel(SootClass.java:191)
	at soot.SootClass.getMethodUnsafe(SootClass.java:580)
	at soot.SootMethodRefImpl.tryResolve(SootMethodRefImpl.java:210)
	at soot.SootMethodRefImpl.resolve(SootMethodRefImpl.java:268)
	at soot.SootMethodRefImpl.resolve(SootMethodRefImpl.java:183)
	at soot.jimple.internal.AbstractInvokeExpr.getMethod(AbstractInvokeExpr.java:56)
	at soot.jimple.validation.InvokeArgumentValidator.validate(InvokeArgumentValidator.java:54)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:118)
	at soot.jimple.JimpleBody.validate(JimpleBody.java:98)
	at soot.PackManager.runBodyPacks(PackManager.java:1011)
	at soot.PackManager.lambda$runBodyPacks$0(PackManager.java:663)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Ouuups... something went wrong! Sorry about that.
Follow these steps to fix the problem:
1.) Are you sure you used the right command line?
    Click here to double-check:
    https://github.com/soot-oss/soot/wiki/Options-and-JavaDoc

2.) Not sure whether it's a bug? Feel free to discuss
    the issue on the Soot mailing list:
    https://github.com/soot-oss/soot/wiki/Getting-help

3.) Sure it's a bug? Click this link to report it.
    https://github.com/soot-oss/soot/issues/new?title=java.lang.RuntimeException+when+...&body=Steps+to+reproduce%3A%0A1.%29+...%0A%0AFiles+used+to+reproduce%3A+%0A...%0A%0ASoot+version%3A+%3Cpre%3Etrunk%3C%2Fpre%3E%0A%0ACommand+line%3A%0A%3Cpre%3E--validate+-f+J+--process-dir+c%2Fout%3C%2Fpre%3E%0A%0AMax+Memory%3A%0A%3Cpre%3E3916MB%3C%2Fpre%3E%0A%0AStack+trace%3A%0A%3Cpre%3Ejava.lang.RuntimeException%3A+This+operation+requires+resolving+level+SIGNATURES+but+soot.dummy.InvokeDynamic+is+at+resolving+level+DANGLING%0AIf+you+are+extending+Soot%2C+try+to+add+the+following+call+before+calling+soot.Main.main%28..%29%3A%0AScene.v%28%29.addBasicClass%28soot.dummy.InvokeDynamic%2CSIGNATURES%29%3B%0AOtherwise%2C+try+whole-program+mode+%28-w%29.%0A%09at+soot.SootClass.checkLevelIgnoreResolving%28SootClass.java%3A212%29%0A%09at+soot.SootClass.checkLevel%28SootClass.java%3A191%29%0A%09at+soot.SootClass.getMethodUnsafe%28SootClass.java%3A580%29%0A%09at+soot.SootMethodRefImpl.tryResolve%28SootMethodRefImpl.java%3A210%29%0A%09at+soot.SootMethodRefImpl.resolve%28SootMethodRefImpl.java%3A268%29%0A%09at+soot.SootMethodRefImpl.resolve%28SootMethodRefImpl.java%3A183%29%0A%09at+soot.jimple.internal.AbstractInvokeExpr.getMethod%28AbstractInvokeExpr.java%3A56%29%0A%09at+soot.jimple.validation.InvokeArgumentValidator.validate%28InvokeArgumentValidator.java%3A54%29%0A%09at+soot.jimple.JimpleBody.validate%28JimpleBody.java%3A118%29%0A%09at+soot.jimple.JimpleBody.validate%28JimpleBody.java%3A98%29%0A%09at+soot.PackManager.runBodyPacks%28PackManager.java%3A1011%29%0A%09at+soot.PackManager.lambda%24runBodyPacks%240%28PackManager.java%3A663%29%0A%09at+java.base%2Fjava.util.concurrent.ThreadPoolExecutor.runWorker%28ThreadPoolExecutor.java%3A1128%29%0A%09at+java.base%2Fjava.util.concurrent.ThreadPoolExecutor%24Worker.run%28ThreadPoolExecutor.java%3A628%29%0A%09at+java.base%2Fjava.lang.Thread.run%28Thread.java%3A834%29%0A%3C%2Fpre%3E
    Please be as precise as possible when giving us
    information on how to reproduce the problem. Thanks!
RESOLVE SootMethod: makeConcatWithConstants [24, Thread-11, 1526460177]
RESOLVE SootMethod: makeConcatWithConstants [25, Thread-12, 1770603249]
$>

Note: the changes in the pom.xml can be ignored.

# Please enter the commit message for your changes. Lines starting
# with '#' will be kept; you may remove them yourself if you want to.
# An empty message aborts the commit.
#
# Date:      Tue Jun 16 11:24:40 2020 +0200
#
# On branch reftype_race_makeClassRef_debug
# Changes to be committed:
#	modified:   ../../../../pom.xml
#	modified:   PackManager.java
#	modified:   Scene.java
#	modified:   SootClass.java
#	modified:   SootMethod.java
#	modified:   SootMethodRefImpl.java
#	modified:   SootResolver.java
#	modified:   asm/AsmMethodSource.java
#
# Untracked files:
#	../../../../diff
#	../../../../pom.diff
#	../../../../pom.xml.orig
#	../../../../repo/
#	.PackManager.java.swp
#	.RefType.java.swp
#	.Scene.java.swp
#	.SootClass.java.swp
#	.SootMethodRefImpl.java.swp
#	.SootResolver.java.swp
#	.session/
#	Scene.java.orig
#	asm/.AsmClassSource.java.swp
#	asm/.AsmMethodSource.java.swp
#	asm/.MethodBuilder.java.swp
#	asm/.SootClassBuilder.java.swp
#	diff
#	jimple/internal/.AbstractInvokeExpr.java.swp
#	jimple/validation/.InvokeValidator.java.swp
#	util/.ArrayNumberer.java.swp
#